### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by YoSarin** [hugobloem/wyoming-microsoft-stt#15]
Hi @hugobloem, I know issue is not correct form probably, but just want to quickly share working dockerfile for this repo: https://gist.github.com/YoSarin/d760699f24e236a9af611df42f289f67

**Comment by hugobloem** [comment]
Hey! Thank you for your interest. You can submit a pull request if you want so I can add it to the repo, and you can be attributed for the contribution.

**Comment by nerijus** [comment]
ping @YoSarin
