### ISSUE TITLE
docker help.

### ISSUE THREAD

**Issue by casacemal** [hugobloem/wyoming-microsoft-stt#52]
How do I run this in casaos program? What should a sample docker compose file look like?
https://casaos.io/

**Comment by hugobloem** [comment]
Hi, I am not familiar with Casa OS but it seems like you should be able to install docker images to it. You could do this or use this command as a pointer to further your search:
```bash
docker pull ghcr.io/hugobloem/wyoming-microsoft-stt-noha:latest
```
